### ISSUE TITLE
Build on Kali Linux

### ISSUE THREAD

**Issue by jivoi** [jtesta/ssh-mitm#1]
Hi there. 
There is a small problem with building OpenSSH on Kali linux with latest version of OpenSSL 1.1.
OpenSSH upstream doesn't support this yet =(
All you need to do is to configure openssh with openssl-1.0.2k.

**Here a small howto:**

**# Download OpenSSL and verify its signature, need it you build OpenSSH on Kali:**
mkdir -p /opt/ssh-mitm && cd /opt/ssh-mitm
wget https://www.openssl.org/source/openssl-1.0.2k.tar.gz
tar xzf openssl-1.0.2k.tar.gz && cd openssl-1.0.2k
./config --prefix=/usr/local/openssl-1.0.2k --openssldir=/usr/local/openssl-1.0.2k && make install

**# Unpack the tarball, patch the sources, and compile it with new **SSLDIR**:**
cd /opt/ssh-mitm
tar xzf openssh-7.5p1.tar.gz
wget https://raw.githubusercontent.com/jtesta/ssh-mitm/master/openssh-7.5p1-mitm.patch
patch -p0 < openssh-7.5p1-mitm.patch
mv openssh-7.5p1 openssh-7.5p1-mitm && cd openssh-7.5p1-mitm && ./configure --with-sandbox=no --with-ssl-dir=/usr/local/openssl-1.0.2k && make -j 5

**Comment by jtesta** [comment]
Thanks for this.  I plan on writing an install script to automate building soon.  I'll take this into consideration to make it easier on the user.

**Comment by jtesta** [comment]
I just released v1.1 of the tool, which features an automatic installer that correctly handles Kali.

FYI, I found that you can install the *libssl1.0-dev* package instead of using the OpenSSL sources directly.  This makes keeping the OpenSSL patches current much easier!

Thanks again for the help!
