### ISSUE TITLE
New functionality

### ISSUE THREAD

**Issue by phschon** [jtesta/ssh-mitm#15]
Hi,

first of all thank you for your work. Your openssh modifications saved me a lot of time.

I added some changes to the patch file that write a timestamp, source IP and source/destination port to the log file. This helped me identifying or observing a communication in e.g. a pcap file or wireshark.

Sample output:
```
Time: 2018-05-30 13:08:44
Hostname: 192.168.0.2:22
Origin: 192.168.0.3:12345
Username: root
Password: root
-------------------------
```

If you are interested, I can create a pull request to merge my changes into your repository.

**Comment by jtesta** [comment]
You're welcome!

And yes, if you submit a PR, I can merge it in.  Thanks!
