### ISSUE TITLE
Installation fails on Ubuntu 20, Debian 10

### ISSUE THREAD

**Issue by jtesta** [jtesta/ssh-mitm#28]
Ubuntu Server 20.04 LTS and Debian 10 both ship with OpenSSL v1.1.1.  This is incompatible with OpenSSH v7.5p1, which the project is based on.  Other newer OSes are likely affected as well.

Fortunately, Ubuntu Server 18.04 LTS and Linux Mint 19 still work.  Use these until a fix is in place (this might be a few months based on my schedule).

**Comment by manfred-kaiser** [comment]
I think, this issue can be closed, because with the docker container, there is no need to install the server on the host system.

**Comment by jtesta** [comment]
Fixed.
