### ISSUE TITLE
Feature Request - Add OpenSSH source instead of patch file

### ISSUE THREAD

**Issue by manfred-kaiser** [jtesta/ssh-mitm#32]
While working with patch files is an easy method to apply changes to existing project, it is hard to maintain and to add new feature.

Also the commit history becomes complicated and adding new features is also hard. 

The original source code has to be compared with the patched source code and adding new features from multiple pull requests could get a pain.

I would suggest to add OpenSSH's source code to the project. If you want, I will create a pull request.

Should I use your new development branch or the master/main branch?

**Comment by manfred-kaiser** [comment]
The pull request #33  is ready to merge ;-)

**Comment by manfred-kaiser** [comment]
Are you interested in this pull request or should we create a new one?

I you are still interested, I can update it to the latest master.

**Comment by manfred-kaiser** [comment]
As described in #39, I can change the docker container to CentOS 7. This allows using the application as a precompiled binary on other systems, with newer libraries.

**Comment by jtesta** [comment]
Done in c1da68f1fe7d7ac610600bff78e98f3bb502e8a8.

I very much appreciate that you took the initiative for this PR, but reviewing it would have taken much longer than simply doing it myself!
