### ISSUE TITLE
MITM doesn't work

### ISSUE THREAD

**Issue by Gregoryash** [jtesta/ssh-mitm#36]
Connection closes after password request, also shows "debug1: Authentication succeeded (password)." despite the fact entered password is incorrect. ssh-mitm is running on Ubuntu 18 as well as the client.
[log.txt](https://github.com/jtesta/ssh-mitm/files/6571391/log.txt)

**Comment by jtesta** [comment]
For now, a workaround is to use the stable release.

What happened is I made some breaking changes about a week ago,
thinking I'd have time to fix them "in the next few hours".  -100
points for me.  :(

**Comment by Gregoryash** [comment]
Thank you very much

**Comment by manfred-kaiser** [comment]
You can try  the version in pull request #33 
This builds and runs jtesta's ssh-mitm in a docker container.

I have tried it successfully on my dev machine and was able to login to another server.

**Comment by manfred-kaiser** [comment]
The log message ``debug1: Authentication succeeded (password).`` comes from your client.

the mitm server accepts the login, without checking the password and tries to authenticate with the entered password. For your client it looks like you are successfully authenticated to the right server. The client does not know, that you are logging in to an mitm server, which accepts all passwords.

Are you using the arp spoofing scripts or do you want to connect without them?

If you want to use the the mitm server without arp spoofing, you have to edit lol.h

Note: When using the current master branch, lol.h is only available, after the patch file is applied to the openssh source code.

When you are using my pull request, you can find lol.h in openssh source code directory (openssh-7.5p1).
Edit this file, and build/rebuild the docker container and it should work.

**Comment by jtesta** [comment]
@Gregoryash This issue should be fully fixed now.  Not only has the master branch build process has been updated, but a Docker image has been published on Dockerhub as well (`docker pull positronsecurity/ssh-mitm`, then see the project README for the recommended command line args to launch it).

Please let me know if you run into any other issues!  Thanks!
