### ISSUE TITLE
scp did not put files in $PWD/ssh_mitm_logs/ sftp_session_* folder.

### ISSUE THREAD

**Issue by cybersecurity-research** [jtesta/ssh-mitm#46]
Hello, 

When I copy files using scp. I can find SCP sessions are logged in $PWD/ssh_mitm_logs/ sftp_session_*.html. And  $PWD/ssh_mitm_logs/ sftp_session_* folder was created. But the file are not put in it. I Tried SFTP. Files is OK in the folder.

So, Do i miss somthing or is that a bug?

Thanks for your help.

**Comment by jtesta** [comment]
Looks like scp transfers aren't being intercepted.  The session
password is, however, so its not a total loss.  But it is still a bug.

I'm gearing up for a new release in the next month.  I'll have it fixed
soon.  Thanks for reporting!

**Comment by cybersecurity-research** [comment]
thanks for answer!
