### ISSUE TITLE
No CVE?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [jtesta/ssh-mitm#5]
I was wondering after reading your README, how is it possible that there is no patch around on SSH? And why all the main distributions are on 7.5p1? Feels like a security breach to me.

Am I right?

**Comment by jtesta** [comment]
Uhhh.... I'm completely lost.

**Comment by jtesta** [comment]
Just to be clear: are you thinking that this is a vulnerability in OpenSSH itself?  In that case, no, there isn't one.  My project only enables a penetration tester to capitalize on a users' common mistake: accepting new server keys without verifying that they are legitimate.
