### ISSUE TITLE
Permission to credit and use in Talk

### ISSUE THREAD

**Issue by korang** [jtesta/ssh-mitm#7]
I would like to give a talk at Derbycon and use you as a reference.  I will give all credit to your patch and instructions during my talk.  Just wanted to get permission from you first.

**Comment by jtesta** [comment]
Sure thing!  What's your talk about?

**Comment by korang** [comment]
Just going over this attack method.  Seems interesting to me how it hasn't been picked up more in the community.

**Comment by jtesta** [comment]
Great to hear!  FYI, I just released v1.1, which includes a tool to easily find victims on a LAN.

If your talk gets recorded and/or its slides get posted, please let me know!
