### ISSUE TITLE
No new auth.log getting generated

### ISSUE THREAD

**Issue by vinod272** [jtesta/ssh-mitm#8]
I deleted auth.log file by mistake.. after that i don't see any logs getting created at all....

**Comment by jtesta** [comment]
Sorry to hear that.  /var/log/auth.log is managed by the system.  Rebooting your machine should create a new one.  I'm sure there's a way to do it without rebooting, but I don't know how offhand.

**Comment by vinod272** [comment]
Thank you..reboot worked
